<<<<<<< HEAD
# Agent 1 Configuration File
# Auto-generated by Dashboard

# Website Scraping Configuration
SCRAPING_CONFIG = {
    'bizbuysell': {
        'max_listings': 1,
        'max_pages': 10,
        'url': 'https://www.bizbuysell.com/businesses-for-sale/',
        'enabled': True
    },
    'bizquest': {
        'max_listings': 1,
        'max_pages': 10,
        'url': 'https://www.bizquest.com/businesses-for-sale/',
        'enabled': True
    },
    'loopnet': {
        'max_listings': 1,
        'max_pages': 10,
        'url': 'https://www.loopnet.com/search/businesses-for-sale/',
        'enabled': True
    }
}

# Output Configuration
OUTPUT_CONFIG = {
    'output_file': 'output/listings.csv',
    'save_intermediate': True,
    'format': 'csv'
}

# Browser Configuration
NUM_LISTINGS = 1  # Auto-set by dashboard
MAX_LISTINGS = 1
HEADLESS_MODE = False
TIMEOUT = 30
RETRY_ATTEMPTS = 3
=======
# agent_1/config.py
"""
Configuration for Business Listing Scraper
Control number of listings per website
"""

# Scraping Configuration
SCRAPING_CONFIG = {
    "bizbuysell": {
        "enabled": True,
        "max_listings": 1,  # Change yeh number
        "max_pages": 3,      # Zyada pages = zyada listings
    },
    "bizquest": {
        "enabled": True,
        "max_listings": 1,  # Change yeh number
        "max_pages": 3,
    },
    "loopnet": {
        "enabled": True,
        "max_listings": 1,  # Change yeh number
        "max_pages": 3,
    }
}

# General Settings
GENERAL_CONFIG = {
    "headless": False,           # False = browser dikhegi
    "delay_between_pages": 3,    # Seconds
    "delay_between_listings": 2, # Seconds
    "timeout": 30,               # Page load timeout
}

# Output Settings
OUTPUT_CONFIG = {
    "output_file": "output/listings.csv",
    "save_intermediate": True,   # Save after each website
}
>>>>>>> 7ba3c8725efb6a2051e9ac9233640be8c397066a
