# Agent 1 Configuration File
# Auto-generated by Dashboard

SCRAPING_CONFIG = {
    'bizbuysell': {
        'max_listings': 1,
        'max_pages': 10,
        'url': 'https://www.bizbuysell.com/businesses-for-sale/',
        'enabled': True
    },
    'bizquest': {
        'max_listings': 1,
        'max_pages': 10,
        'url': 'https://www.bizquest.com/businesses-for-sale/',
        'enabled': True
    },
    'loopnet': {
        'max_listings': 1,
        'max_pages': 10,
        'url': 'https://www.loopnet.com/search/businesses-for-sale/',
        'enabled': True
    }
}

OUTPUT_CONFIG = {
    'output_file': 'output/listings.csv',
    'save_intermediate': True,
    'format': 'csv'
}

NUM_LISTINGS = 1
MAX_LISTINGS = 1
HEADLESS_MODE = False
TIMEOUT = 30
RETRY_ATTEMPTS = 3
